[project]
name = "sql-spaced-repeatition-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "duckdb>=1.2.1",
    "pylint>=3.3.6",
    "streamlit>=1.44.0",
]
